---
title: WRARQ
timezone: UTC
collections:
  menu:
    title: Menu
    output: false
    label: menu
  projects:
    title: PROJETOS
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
