# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: '_uploads'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: "Gallery",
          name: "images",
          widget: "list",
          field: { label: Image, name: image, widget: image }
        }